language: node_js
node_js:
- stable
- '6'
- '5'
- '4'
- '0.12'
before_install:
- npm install -g codecov
script:
- npm test && codecov
notifications:
  email: false
deploy:
  provider: npm
  email: sinsoku.listy@gmail.com
  api_key:
    secure: lWOZmcRN4ROLce1aAn5PQQ/dbnC1jKJB3qwW5o28KwCsgq4x2bGPxlhSWAbp4Pci9RIqJsFUoFr/f82xMLTRxW5cl5XnTd+g8UGucs0V9hFBouTEx3gjxetRKhX2CGSINOoEEKzK4dAnsfDehEYsWRHFdbvyrE/lmbMQetXPFlIvhGKZQwz4GLfsN/IX2Qr1Eus5GaTxhah2x0PpdFLh6/b2vLSsiHoFxWTFFufNZmvUV2bb55H6VUKzl/20cmSXpYipj3LnNUNGRyQJL+FF0LLL/DymIsZxuJMfVWo/e0C26WN8+/S0o/um/L2dwRm2qpwqhDpDPCFK32rczhk1MBRMhmhxdP8DOW7GZtSOD5Lfr05Jd+bxDIWmZDvgZrvBWbxtLmrDU5jNa/R7hS6bP8h9daOvJXo3ZH8lYd/7wMnEk+z0lv1IqwLwy7c3ZjXyfcaVR6p89+zMCU2Wpsj8/ZfyFs7PT84vgw0sN9iBFfNDU4CBoTZJLMaAKGdCEli3irFRlGWUDYl3OA0UrlAl5ke1jC4BF3Mhpe7a3bVv3ySkNCP6ZjYgX94hJ6eq7eX5MsP6G82TqzSp9BLSuDWXWn20Ko3mc635ImhdfL4RWZUoCPmC0z8Dc4xA7CeyJj0sCTRiA20eTMnaC3xFl49nicf6viF4I16C101cf8Fz0/E=
  on:
    tags: true
